### ISSUE TITLE
重影

### ISSUE THREAD

**Issue by liyongjie1002** [shanghaiMichael/DYYFloatWindow#1]
用在自己的项目中，悬浮按钮移动时出现重影

**Comment by liyongjie1002** [comment]
问题出在使用导航控制器，根视图为一个UIViewController。移动按钮出现重影。而单独使用一个UIViewController正常显示

**Comment by shanghaiMichael** [comment]
我在NavigationController下试了并没有出现重影，能写个demo重现后发我吗？

**Comment by liyongjie1002** [comment]
好的，稍等

**Comment by lyjpost** [comment]
怎么发给你

**Comment by liyongjie1002** [comment]
- 
  [Uploading NavigationTest.zip…]()

**Comment by liyongjie1002** [comment]
在storyboard中把uiviewcontroller直接转换成navigationcontroller

**Comment by liyongjie1002** [comment]
代码创建的没问题
